-- 상황별 회화 예문 (AI Hub 한-일 번역 병렬 말뭉치에서 고른 64,000문장)
-- 1) Supabase 대시보드 > SQL Editor에 붙여넣고 한 번 실행
-- 2) Table Editor > corpus > Insert > Import data from CSV 로 data/tutor_corpus.csv 올리기
--    (scripts/build_tutor_corpus.py 로 만든 파일, id 열은 비워 두면 자동)
--
-- 데이터셋은 재배포가 제한되므로 테이블을 직접 읽을 수 없게 막고(RLS),
-- 로그인한 사용자가 아래 함수로 한 번에 최대 20문장만 가져갈 수 있게 한다.

-- Supabase는 확장 기능을 extensions 영역에 두므로 거기에 설치하고, 아래에서 이름을 붙여 씀
create extension if not exists pg_trgm with schema extensions;

create table if not exists public.corpus (
  id bigint generated by default as identity primary key,
  situation text not null,   -- airport·hotel·restaurant·shopping·sightseeing·leisure·sports·daily
  source_id bigint,          -- 원본 데이터셋 ID
  direction text,            -- ko-ja(한국어 원문) | ja-ko(일본어 원문)
  topic text,                -- 원본 소분류
  kind text,                 -- 문의 | 답변 | ''
  ko text not null,
  ja text not null
);
create index if not exists corpus_situation_idx on public.corpus (situation);
create index if not exists corpus_ko_trgm on public.corpus using gin (ko extensions.gin_trgm_ops);
create index if not exists corpus_ja_trgm on public.corpus using gin (ja extensions.gin_trgm_ops);

alter table public.corpus enable row level security;
-- 정책을 만들지 않으므로 anon·authenticated 모두 직접 select 불가

-- 상황별 예문 찾기 — p_query가 비면 무작위, 있으면 한국어·일본어 어느 쪽이든 비슷한 문장 순
create or replace function public.search_corpus(p_situation text, p_query text default null, p_limit int default 8)
returns table (id bigint, ko text, ja text, kind text)
language plpgsql security definer set search_path = public, extensions as $$
declare q text := nullif(trim(coalesce(p_query, '')), '');
begin
  if auth.uid() is null then raise exception 'not logged in'; end if;
  p_limit := greatest(1, least(coalesce(p_limit, 8), 20));
  if q is null then
    return query
      select c.id, c.ko, c.ja, c.kind from corpus c
      where p_situation is null or c.situation = p_situation
      order by random() limit p_limit;
  else
    -- <% 기본 기준(0.6)은 짧은 질문에 너무 엄격해서 낮춤 (이 트랜잭션에서만)
    perform set_config('pg_trgm.word_similarity_threshold', '0.3', true);
    return query
      select c.id, c.ko, c.ja, c.kind from corpus c
      where (p_situation is null or c.situation = p_situation)
        and (q <% c.ko or q <% c.ja)
      order by greatest(word_similarity(q, c.ko), word_similarity(q, c.ja)) desc
      limit p_limit;
  end if;
end $$;

revoke all on function public.search_corpus(text, text, int) from public, anon;
grant execute on function public.search_corpus(text, text, int) to authenticated;
